// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: primepb/prime.proto

package primepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NumReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int64 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *NumReq) Reset() {
	*x = NumReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primepb_prime_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NumReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumReq) ProtoMessage() {}

func (x *NumReq) ProtoReflect() protoreflect.Message {
	mi := &file_primepb_prime_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumReq.ProtoReflect.Descriptor instead.
func (*NumReq) Descriptor() ([]byte, []int) {
	return file_primepb_prime_proto_rawDescGZIP(), []int{0}
}

func (x *NumReq) GetNum() int64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Facto int32 `protobuf:"varint,1,opt,name=facto,proto3" json:"facto,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_primepb_prime_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_primepb_prime_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_primepb_prime_proto_rawDescGZIP(), []int{1}
}

func (x *Res) GetFacto() int32 {
	if x != nil {
		return x.Facto
	}
	return 0
}

var File_primepb_prime_proto protoreflect.FileDescriptor

var file_primepb_prime_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f,
	0x6d, 0x70, 0x6f, 0x22, 0x1a, 0x0a, 0x06, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x22,
	0x1b, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x61, 0x63, 0x74, 0x6f, 0x32, 0x44, 0x0a, 0x0c,
	0x50, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x12, 0x34, 0x0a, 0x05,
	0x70, 0x72, 0x69, 0x6d, 0x65, 0x12, 0x14, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x44, 0x65, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x2e, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x70, 0x72,
	0x69, 0x6d, 0x65, 0x44, 0x65, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x30, 0x01, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x65, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_primepb_prime_proto_rawDescOnce sync.Once
	file_primepb_prime_proto_rawDescData = file_primepb_prime_proto_rawDesc
)

func file_primepb_prime_proto_rawDescGZIP() []byte {
	file_primepb_prime_proto_rawDescOnce.Do(func() {
		file_primepb_prime_proto_rawDescData = protoimpl.X.CompressGZIP(file_primepb_prime_proto_rawDescData)
	})
	return file_primepb_prime_proto_rawDescData
}

var file_primepb_prime_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_primepb_prime_proto_goTypes = []interface{}{
	(*NumReq)(nil), // 0: primeDecompo.NumReq
	(*Res)(nil),    // 1: primeDecompo.Res
}
var file_primepb_prime_proto_depIdxs = []int32{
	0, // 0: primeDecompo.PrimeDecompo.prime:input_type -> primeDecompo.NumReq
	1, // 1: primeDecompo.PrimeDecompo.prime:output_type -> primeDecompo.Res
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_primepb_prime_proto_init() }
func file_primepb_prime_proto_init() {
	if File_primepb_prime_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_primepb_prime_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NumReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_primepb_prime_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_primepb_prime_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_primepb_prime_proto_goTypes,
		DependencyIndexes: file_primepb_prime_proto_depIdxs,
		MessageInfos:      file_primepb_prime_proto_msgTypes,
	}.Build()
	File_primepb_prime_proto = out.File
	file_primepb_prime_proto_rawDesc = nil
	file_primepb_prime_proto_goTypes = nil
	file_primepb_prime_proto_depIdxs = nil
}
