// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: maxpb/max.proto

package maxpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Req struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Num int32 `protobuf:"varint,1,opt,name=Num,proto3" json:"Num,omitempty"`
}

func (x *Req) Reset() {
	*x = Req{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxpb_max_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Req) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Req) ProtoMessage() {}

func (x *Req) ProtoReflect() protoreflect.Message {
	mi := &file_maxpb_max_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Req.ProtoReflect.Descriptor instead.
func (*Req) Descriptor() ([]byte, []int) {
	return file_maxpb_max_proto_rawDescGZIP(), []int{0}
}

func (x *Req) GetNum() int32 {
	if x != nil {
		return x.Num
	}
	return 0
}

type Res struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max int32 `protobuf:"varint,1,opt,name=Max,proto3" json:"Max,omitempty"`
}

func (x *Res) Reset() {
	*x = Res{}
	if protoimpl.UnsafeEnabled {
		mi := &file_maxpb_max_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Res) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Res) ProtoMessage() {}

func (x *Res) ProtoReflect() protoreflect.Message {
	mi := &file_maxpb_max_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Res.ProtoReflect.Descriptor instead.
func (*Res) Descriptor() ([]byte, []int) {
	return file_maxpb_max_proto_rawDescGZIP(), []int{1}
}

func (x *Res) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

var File_maxpb_max_proto protoreflect.FileDescriptor

var file_maxpb_max_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x70, 0x62, 0x2f, 0x6d, 0x61, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x6d, 0x61, 0x78, 0x70, 0x62, 0x22, 0x17, 0x0a, 0x03, 0x52, 0x65, 0x71, 0x12,
	0x10, 0x0a, 0x03, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4e, 0x75,
	0x6d, 0x22, 0x17, 0x0a, 0x03, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x61, 0x78, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x4d, 0x61, 0x78, 0x32, 0x2e, 0x0a, 0x03, 0x41, 0x50,
	0x49, 0x12, 0x27, 0x0a, 0x07, 0x46, 0x69, 0x6e, 0x64, 0x4d, 0x61, 0x78, 0x12, 0x0a, 0x2e, 0x6d,
	0x61, 0x78, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x1a, 0x0a, 0x2e, 0x6d, 0x61, 0x78, 0x70, 0x62,
	0x2e, 0x52, 0x65, 0x73, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f,
	0x6d, 0x61, 0x78, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_maxpb_max_proto_rawDescOnce sync.Once
	file_maxpb_max_proto_rawDescData = file_maxpb_max_proto_rawDesc
)

func file_maxpb_max_proto_rawDescGZIP() []byte {
	file_maxpb_max_proto_rawDescOnce.Do(func() {
		file_maxpb_max_proto_rawDescData = protoimpl.X.CompressGZIP(file_maxpb_max_proto_rawDescData)
	})
	return file_maxpb_max_proto_rawDescData
}

var file_maxpb_max_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_maxpb_max_proto_goTypes = []interface{}{
	(*Req)(nil), // 0: maxpb.Req
	(*Res)(nil), // 1: maxpb.Res
}
var file_maxpb_max_proto_depIdxs = []int32{
	0, // 0: maxpb.API.FindMax:input_type -> maxpb.Req
	1, // 1: maxpb.API.FindMax:output_type -> maxpb.Res
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_maxpb_max_proto_init() }
func file_maxpb_max_proto_init() {
	if File_maxpb_max_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_maxpb_max_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Req); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_maxpb_max_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Res); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_maxpb_max_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_maxpb_max_proto_goTypes,
		DependencyIndexes: file_maxpb_max_proto_depIdxs,
		MessageInfos:      file_maxpb_max_proto_msgTypes,
	}.Build()
	File_maxpb_max_proto = out.File
	file_maxpb_max_proto_rawDesc = nil
	file_maxpb_max_proto_goTypes = nil
	file_maxpb_max_proto_depIdxs = nil
}
